export { default as Headline } from './Headline'
export { default as ProductList } from './ProductList'
export { default as Carousel } from './Carousel'
export { default as NewArrivals } from './NewArrivals'
export { default as TopCategories } from './TopCategories'
export { default as TopRatings } from './TopRatings'
export { default as FeaturedBrands } from './FeaturedBrands'
export { default as Delivery } from './Delivery'
